name: Matrix
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  format:
    name: Format
    runs-on: native
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - run: cargo fmt --all -- --check

  clippy:
    name: Clippy check
    runs-on: native
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - run: cargo clippy --all-targets -- -D warnings

  build:
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly

    name: Build - ${{matrix.rust}}
    runs-on: native
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{matrix.rust}}
          components: rustfmt, clippy
      - run: cargo build

  test:
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly

    name: Test - ${{matrix.rust}}
    runs-on: native
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{matrix.rust}}
          components: rustfmt, clippy
      - run: cargo build

